### ISSUE TITLE
Media Mod does not detect songs and also displays time incorrectly

### ISSUE THREAD

**Issue by NinjaShuriken** [MediaModMC/MediaMod#52]
So a lot of the time the media mod does not detect the music playing on Youtube Music, when it DOES detect it it adds 30mins to each side so if it is actually at 1:15/2:15 it would show 31:15/32:15

Simply install the mod with latest version of forge on MC 1.8.9

I expected it to simply pick up the songs from music.youtube.com and show me a player in the top left with the correct time, lately it hasn't been detecting the songs and when it does detect them it shows wrong time

I would add screenshots but I cannot as it hasn't shown me the player

Doesn't work on Windows or Linux for me

I was using Youtube Music as stated above

**Comment by cbyrne** [comment]
Hey!

At the moment for v2 of MediaMod - the extension and a lot of the Mod is being rewritten to be better than ever. This has been fixed in the rewrite of the browser extension, which will be available when v2 of the mod goes live.

You can see more information about the new browser extension here: https://github.com/MediaModMC/Extension/commit/07a309b582a882d847a7a052b933e4a1caac46e5
